/**
 * UI 文言の唯一の定義元。
 * コンポーネント内に日本語リテラルを直接書かず、ここを参照する。
 */
export const LABELS = {
  app: {
    name: 'Kiroku',
  },
  nav: {
    entry: '経費入力',
    list: '経費一覧',
    settings: '設定',
    /** メニューには出さないが画面見出しには使う */
    detail: '経費照会',
    toggleOpen: 'メニューを開く',
    toggleClose: 'メニューを折りたたむ',
  },
  common: {
    save: '保存',
    saveAndContinue: '保存して続けて入力',
    update: '更新',
    cancel: 'キャンセル',
    close: '閉じる',
    delete: '削除',
    edit: '編集',
    duplicate: '複製',
    add: '追加',
    search: '検索',
    reset: 'リセット',
    open: '開く',
    select: '選択',
    loading: '読み込んでいます…',
    processing: '処理しています…',
    noData: 'データがありません',
    required: '必須',
    optional: '任意',
    yes: 'はい',
    no: 'いいえ',
    confirm: '確認',
    unset: '未設定',
    moveUp: '上へ',
    moveDown: '下へ',
    enabled: '有効',
    disabled: '無効',
    back: '戻る',
    next: '次へ',
    previous: '前へ',
    finish: '完了',
    detail: '照会',
  },
  entry: {
    titleCreate: '経費を入力',
    titleEdit: '経費を編集',
    description: '領収書の内容を記録します。同じ請求元は次回から自動で補完されます。',
    date: '日付',
    accountCategory: '勘定科目',
    accountCategoryHint: '判断がつかない場合は未設定のままで登録できます。税理士に確認してもらってください。',
    payee: '請求元',
    payeePlaceholder: '例：〇〇株式会社',
    amount: '金額',
    amountUnit: '円',
    taxTreatment: '税区分',
    taxRate: '税率',
    paymentMethod: '支払方法',
    allocation: '按分設定',
    allocationRate: '事業按分率',
    allocationHint: '金額 × 按分率 が経費計上額になります',
    allocationNone: '按分なし（税理士に依頼する）',
    allocationNoneHint:
      '按分率を 100% として保存し、按分の判断を税理士に委ねる旨を備考へ自動で追記します。',
    content: '内容',
    contentPlaceholder: '例：打ち合わせの交通費',
    note: '備考',
    attachments: '領収書',
    attachmentAdd: 'ファイルを追加',
    attachmentPaste: 'クリップボードから貼り付け',
    attachmentFromFolder: '取り込みフォルダから選ぶ',
    attachmentDropHint:
      'ドラッグ&ドロップ、Ctrl+V での貼り付けにも対応（大きな画像は保存時に自動で縮小します）',
    attachmentPasted: '貼り付けた画像を添付しました。',
    attachmentRemove: '添付を外す',
    /* 添付一覧の下に出す、画像・PDF を 1 枚ずつ見るプレビューの文言 */
    attachmentPreviewPosition: '{current} / {total} 枚目',
    attachmentPreviewPrevious: '前のファイル',
    attachmentPreviewNext: '次のファイル',
    attachmentPreviewZoom: 'クリックすると別ウィンドウで大きく表示します',
    attachmentPreviewUnsupported: 'この形式は画面に表示できません。',
    attachmentPreviewFailed: 'ファイルを表示できませんでした。',
    attachmentOpenExternal: '既定のアプリで開く',
    preview: '計算結果',
    previewTaxExcluded: '税抜額',
    previewTax: '消費税額',
    previewTaxIncluded: '税込額',
    previewAllocated: '経費計上額',
    assistApplied: '前回の入力から自動補完しました',
    assistBadge: '自動補完',
    createdMessage: '経費を登録しました。',
    updatedMessage: '経費を更新しました。',
    suggestionsHeading: '過去に使った内容',
  },
  list: {
    title: '経費一覧',
    description: '対象期間を切り替えて確認し、そのままExcelに出力できます。',
    periodMode: '期間',
    periodYear: '年',
    periodMonth: '月',
    modeYear: '年単位',
    modeMonth: '月単位',
    filterCategory: '勘定科目',
    filterPayee: '請求元',
    filterKeyword: 'キーワード',
    filterKeywordPlaceholder: '内容・備考・請求元で検索',
    filterAll: 'すべて',
    /** 領収書（画像・PDF）の添付有無での絞り込み */
    filterAttachment: '領収書',
    filterAttachmentPresent: '添付あり',
    filterAttachmentAbsent: '添付なし',
    download: 'Excelでダウンロード',
    downloading: 'Excelを作成しています…',
    downloaded: 'Excelを出力しました。',
    downloadCanceled: '出力をキャンセルしました。',
    csvImport: 'CSVから取り込み',
    count: '件数',
    totalTaxIncluded: '合計（税込）',
    totalTaxExcluded: '合計（税抜）',
    totalTax: '消費税合計',
    totalAllocated: '経費計上額合計',
    categoryBreakdown: '勘定科目別の内訳',
    empty: '対象期間に登録された経費はありません。',
    deleteConfirmTitle: '経費を削除しますか？',
    deleteConfirmBody: '削除すると元に戻せません。添付した領収書ファイルも削除されます。',
    deletedMessage: '経費を削除しました。',
    /**
     * 一覧の列。ここに載せない項目（内容・支払方法・税抜額・消費税額・按分率・
     * 経費計上額）は経費照会画面で確認する。
     * 領収書は中身までは出さず、添付されているかどうかだけを示す。
     */
    columns: {
      date: '日付',
      accountCategory: '勘定科目',
      payee: '請求元',
      amount: '金額（税込）',
      tax: '税区分 / 税率',
      attachment: '領収書',
      actions: '操作',
    },
    /** 領収書の列に出す表示。添付ありは枚数を添える */
    attachmentPresent: 'あり（{count}）',
    attachmentAbsent: 'なし',
    pagination: {
      label: 'ページ送り',
      status: '{total} 件中 {start}〜{end} 件を表示',
      page: '{current} / {total} ページ',
    },
  },
  detail: {
    title: '経費照会',
    description: '内容を確認し、その場で修正できます。',
    notFound: '対象の経費が見つかりませんでした。',
    allocationDelegated: '按分なし（税理士に依頼）',
    createdAt: '登録日時',
    updatedAt: '更新日時',
    backToList: '一覧に戻る',
    previousReceipt: '前の領収書',
    nextReceipt: '次の領収書',
    /** 絞り込み結果の中での位置 */
    position: '{current} / {total} 件目',
    unsavedTitle: '編集中の内容を破棄しますか？',
    unsavedBody: '保存していない変更があります。移動すると変更は失われます。',
    discardAndMove: '破棄して移動',
  },
  terms: {
    title: '利用規約',
    lead: 'ご利用の前に、以下をお読みください。すべてに同意いただける場合のみお使いいただけます。',
    agree: '上記のすべてに内容を確認のうえ同意します',
    accept: '同意して始める',
    decline: '同意しない（終了）',
    version: '規約バージョン',
    /** 一度同意したあとに規約が改定された場合に出す案内 */
    updatedNotice: '利用規約が更新されました。内容をご確認のうえ、改めて同意をお願いします。',
    settingsLabel: '同意済みの利用規約',
    settingsAgreedAt: 'バージョン {version} に同意済み',
    review: '利用規約を読み返す',
  },
  setup: {
    title: '初期セットアップ',
    description: 'はじめに、よく使う項目と保存先を決めておきます。あとから設定画面で変更できます。',
    stepLabel: 'ステップ',
    stepPresets: 'プリセット・表示の設定',
    stepPresetsDescription:
      '経費入力で選ぶ勘定科目と支払方法、入力時の初期値を決めます。使わない項目は無効にできます。',
    stepExport: '出力設定',
    stepExportDescription:
      '税理士へ渡す Excel の保存先とファイル名を決めます。保存時にこの場所が最初に開きます。',
    stepBackup: 'バックアップ先の設定',
    stepBackupDescription:
      '万一に備えてデータの控えを残します。起動時に自動で取得しておくと安心です。',
    finish: 'この内容ではじめる',
    completedMessage: '初期セットアップが完了しました。',
    welcomeTitle: 'ようこそ、Kiroku へ',
    welcomeMessage:
      '初期セットアップが完了しました。さっそく領収書をキロクしていきましょう。設定はあとからいつでも変更できます。',
    welcomeStart: 'はじめる',
    /** 各画面の使い方。キーはサイドメニューの画面 ID と対応させる */
    welcomeGuides: {
      entry: '領収書の内容を記録します。同じ請求元は次回から自動で補完されます。',
      list: '期間を切り替えて確認し、そのまま Excel に出力できます。',
      settings: 'プリセットやバックアップ先はいつでも変更できます。',
    },
    restart: '初期セットアップをやり直す',
    restartConfirmTitle: '初期セットアップをやり直しますか？',
    restartConfirmBody:
      '登録済みの経費・領収書ファイル・請求元の記憶をすべて削除し、セットアップ画面を開き直します。' +
      'この操作は取り消せません。削除の直前に自動でバックアップを取得するので、' +
      '元に戻したい場合は設定画面の「バックアップ履歴」から復元してください。' +
      '（勘定科目・支払方法などの設定は残ります）',
    restartConfirmLabel: 'データを削除してやり直す',
    /** 削除件数とバックアップ先を伝える */
    restartDone: '経費データを {count} 件削除しました。直前のバックアップ：{backup}',
  },
  settings: {
    title: '設定',
    description: 'データの保護と入力のしやすさを調整します。',
    sectionData: 'データ管理',
    sectionPresets: 'プリセットの設定',
    sectionExport: '出力設定',
    sectionDisplay: '表示設定',
    backupEnabledOnStartup: '起動時に自動バックアップする',
    backupDirectory: 'バックアップ先',
    backupRetentionCount: '保持する世代数',
    backupIncludeAttachments: '領収書ファイルもバックアップに含める',
    backupRunNow: '今すぐバックアップ',
    backupList: 'バックアップ履歴',
    backupEmpty: 'バックアップはまだありません。',
    backupCreated: 'バックアップを作成しました。',
    restore: '復元',
    restoreConfirmTitle: 'このバックアップから復元しますか？',
    restoreConfirmBody:
      '現在のデータはバックアップ時点の内容に置き換わります。復元の直前に、現在の状態を自動でバックアップします。',
    restored: '復元しました。',
    startupBackupSucceeded: '起動時バックアップを実行しました。',
    startupBackupFailed: '起動時バックアップに失敗しました。',
    storageLocations: 'データの保存場所',
    databasePath: 'データベース',
    attachmentsDirectory: '領収書ファイル',
    openFolder: 'フォルダを開く',
    accountCategories: '勘定科目',
    paymentMethods: '支払方法',
    presetName: '名称',
    presetDefaultAllocation: '既定の按分率',
    presetActive: '有効',
    presetAdd: '追加する',
    presetNamePlaceholder: '新しい項目名',
    presetSaved: 'プリセットを更新しました。',
    presetDeleted: 'プリセットを削除しました。',
    presetDeleteConfirmTitle: 'このプリセットを削除しますか？',
    presetDeleteConfirmBody: '使用中のプリセットは削除できません。その場合は無効化してください。',
    exportDirectory: 'Excelの既定保存先',
    sectionImport: '領収書の取り込み元',
    importDirectory: '取り込みフォルダ',
    importDirectoryHint:
      'スマートフォンから送った画像の置き場所です。Bluetooth の受信先や、iCloud・OneDrive・Google ドライブの同期フォルダを指定すると、経費入力画面から選んで添付できます。',
    exportFileNameTemplate: 'ファイル名テンプレート',
    exportTemplateHint: '使えるプレースホルダ：',
    defaultTaxTreatment: '既定の税区分',
    defaultTaxRate: '既定の税率',
    defaultAllocationRate: '既定の按分率',
    defaultPeriodMode: '経費一覧の既定期間',
    sideMenuState: 'サイドメニュー',
    sideMenuCollapsed: '折りたたみ中',
    sideMenuExpanded: '展開中',
    saved: '設定を保存しました。',
    useDefault: '既定の場所を使う',
  },
  importPicker: {
    title: '取り込みフォルダから選ぶ',
    description:
      'スマートフォンから Bluetooth やクラウド同期で送った画像を、このフォルダ経由で添付できます。',
    folderLabel: '取り込みフォルダ',
    openFolder: 'フォルダを開く',
    reload: '再読み込み',
    empty: 'このフォルダに取り込めるファイルがありません。',
    notConfigured:
      '取り込みフォルダにファイルが見つかりません。設定画面の「領収書の取り込み元」で、Bluetooth の受信先やクラウド同期先を指定してください。',
    noThumbnail: 'プレビューなし',
    selectedCount: '{count} 件を選択中',
    attach: '選択したファイルを添付',
    limitNote: '新しい順に最大 {max} 件まで表示します。',
  },
  csvImport: {
    title: 'CSVから経費を取り込む',
    description:
      '内容を確認してから登録します。1行目は見出し行として扱われ、テンプレートと同じ並びである必要があります。',
    downloadTemplate: 'テンプレートをダウンロード',
    selectFile: 'CSVファイルを選択',
    parsing: 'CSVを読み込んでいます…',
    fileName: 'ファイル',
    okCount: '取り込み可能',
    errorCount: 'エラー',
    unitRows: '行',
    columns: {
      row: '行',
      date: '日付',
      category: '勘定科目',
      payee: '請求元',
      amount: '金額',
      tax: '税区分・税率',
      allocation: '按分率',
      description: '内容',
      error: 'エラー内容',
    },
    noErrorRows: 'エラーのある行はありません。',
    import: 'この内容で取り込む',
    importing: '経費を登録しています…',
    noImportableRows: '取り込める行がありません。',
    committed: '{imported} 件を取り込みました。',
    committedWithFailures: '{imported} 件を取り込みました（{failed} 件は登録できませんでした）。',
    templateDownloaded: 'テンプレートを保存しました。',
    templateDownloadCanceled: 'テンプレートの保存をキャンセルしました。',
    parseCanceled: 'ファイルの選択をキャンセルしました。',
  },
  errors: {
    generic: 'エラーが発生しました。',
    loadFailed: 'データの読み込みに失敗しました。',
  },
} as const;
